services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: taskflow-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskflow"]
      interval: 5s    # testa a cada 5 segundos
      timeout: 5s     # espera até 5s pela resposta
      retries: 5      # tenta 5 vezes antes de considerar unhealthy
      start_period: 10s  # dá 10s pro container inicializar antes de começar a testar
    volumes:
      - taskflow-pgdata:/bitnami/postgresql
      - taskflow-initdb:/docker-entrypoint-initdb.d
      - taskflow-preinitdb:/docker-entrypoint-preinitdb.d

volumes:
  taskflow-pgdata:
    name: taskflow-pgdata
  taskflow-initdb:
    name: taskflow-initdb
  taskflow-preinitdb:
    name: taskflow-preinitdb


