import {
    AlignStartHorizontal,
    Clock,
    Crown,
    Inbox,
    Mail,
    StickyNote,
} from "lucide-react";

export const NOTIFICATIONS_LIST = [
  {
    id: "123",
    path: "/notifications",
    icon: Clock,
    text: "Uma tarefa vence hoje: Protótipo de navegação mobile",
    desc: "NovoBoard - App Mobile · 16:42",
    button: false,
    readed: false,
  },
  {
    id: "567",
    path: "/notifications",
    icon: Mail,
    text: "Marina Duarte convidou você para um workspace: Coletivo Design Lab",
    desc: "15h",
    button: true,
    readed: false,
  },
  {
    id: "521",
    path: "/notifications",
    icon: Inbox,
    text: "Beatriz Lima atribuiu uma tarefa a você: Autoria de acessibilidade",
    desc: "NovoBoard - App Mobile · 17h",
    button: false,
    readed: false,
  },
  {
    id: "783",
    path: "/notifications",
    icon: StickyNote,
    text: "Nina Castro moveu uma tarefa: Design do ícone do app",
    desc: "NovoBoard - App Mobile · 2d",
    button: false,
    readed: true,
  },
  {
    id: "356",
    path: "/notifications",
    icon: Crown,
    text: "Lara Pires promoveu você a admin em Produto NeoPay",
    desc: "2d",
    button: false,
    readed: true,
  },
  {
    id: "086",
    path: "/notifications",
    icon: AlignStartHorizontal,
    text: "Théo Almeida Criou um novo board: Clientes 2026",
    desc: "Projetos freelance · 3d",
    button: false,
    readed: true,
  },
];
